### ISSUE TITLE
maze2D weights

### ISSUE THREAD

**Issue by ConstantinosM** [jannerm/diffuser#13]
Hi and thank you for sharing the code of this very interesting work!

Do you intend to share the maze2D weights? In the google folder with the trained models there is no trained model for the maze2d. Am I missing something?

Running the `plan_maze2d.py` I get the following error:
`FileNotFoundError: [Errno 2] No such file or directory: 'logs/maze2d-large-v1/diffusion/H384_T256/model_config.pkl'`

My folder structure after running the script:
![image](https://user-images.githubusercontent.com/25111975/193337541-078f9969-b158-4135-b307-650f8928be43.png)

Any help would be great!

**Comment by jannerm** [comment]
[Here](https://www.dropbox.com/s/za14rwp8to1bosn/maze2d-logs.zip?dl=0) are pretrained weights for the Maze2D environments. They will work with the current `maze2d` branch. Because the `main` branch has been refactored, I will need to retrain them for compatibility before adding them to the main Google Drive folder.
