### ISSUE TITLE
Code's defaults hyperparameters inconsistent with the paper's

### ISSUE THREAD

**Issue by dolts4444** [jannerm/diffuser#20]
Hi.
I found the code's defaults hyperparameters is inconsistent with the paper's such as diffusion steps N=100 in paper but N=20 in code and guide scale, gamma, train step. I wonder how much this will affect performance and if the code's hyperparameters is enough to obtain results reported in paper. Thanks if anyone can give me some helps.

**Comment by jannerm** [comment]
I reduced the number of denoising steps from 100 to 20 to speed up planning for the code release. This required re-tuning a few other hyperparameters, but the average performance for the new defaults (77.5) is slightly higher than that reported for the original, much slower hyperparameters (75.3).

The current main branch should give the following numbers (reported over 150 seeds per environment):

<img width="1064" alt="updated_scores" src="https://user-images.githubusercontent.com/10070626/204204893-b4654c97-d811-4bff-b5f1-ee502461137f.png">

I'll be updating the appendix of the arxiv version soon to match the defaults in this repo. In the meantime, I'd recommend using the current repo defaults because they are faster and yield at least as high performance.

**Comment by dolts4444** [comment]
It's such an amazing work. Thanks a lot for you reply.
